name: Daily Thought Update

on:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 5:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-thought:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: python update_thought.py
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update daily thought"
          git push

